apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nexus-itsm-ingress
  namespace: nexus-itsm
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nexus-itsm
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 27017
        - protocol: TCP
          port: 8501
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
